services:
  krakend:
    container_name: krakend
    image: devopsfaith/krakend:2.7.1
    ports:
      - 4010:8080
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    networks:
      - gateway

  green:
    container_name: green
    build:
      dockerfile: Dockerfile-green
    ports:
      - 4011:80
    networks:
      - gateway

  red:
    container_name: red
    build:
      dockerfile: Dockerfile-red
    ports:
      - 4012:80
    networks:
      - gateway

networks:
  gateway:
    driver: bridge
