FROM golang:1.22.5-alpine3.19 AS builder

WORKDIR /opt

COPY . .

RUN go env -w GOOS=linux
RUN go env -w GOARCH=amd64
RUN go build -o red ./cmd/server

FROM golang:1.22.5-alpine3.19

WORKDIR /opt

COPY --from=builder /opt/red .

EXPOSE 80
CMD ["/opt/red"]
