---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  labels:
    app: krakend
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1
  template:
    metadata:
      labels:
        app: krakend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: krakend
        image: "{{IMAGE}}"
        ports:
        - containerPort: 8080
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
          requests:
            memory: 128Mi
            cpu: 50m
